-- Enable RLS
alter table auth.users enable row level security;

-- Profiles
create table public.profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  full_name text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Lifts (The types of lifts, e.g. Bench Press, Squat)
create table public.lift_types (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  category text -- 'Strength', 'Cardio', etc.
);

alter table public.lift_types enable row level security;

create policy "Lift types are viewable by everyone."
  on lift_types for select
  using ( true );
  
-- Logs (The actual workout entries)
create table public.logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  lift_type_id bigint references public.lift_types(id) on delete cascade,
  lift_name text, -- In case they do a custom lift not in types, or just denormalized
  weight numeric not null,
  unit text default 'lbs', -- 'lbs' or 'kg'
  reps int not null,
  rpe int, -- Rate of Perceived Exertion (1-10)
  body_weight numeric, -- Body weight at time of lift
  date_logged timestamp with time zone default timezone('utc'::text, now()) not null,
  notes text,
  is_pr boolean default false
);

alter table public.logs enable row level security;

create policy "Logs are viewable by everyone."
  on logs for select
  using ( true );

create policy "Users can insert their own logs."
  on logs for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own logs."
  on logs for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own logs."
  on logs for delete
  using ( auth.uid() = user_id );

-- Database Functions
-- Auto-create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed Data (Lift Types)
insert into public.lift_types (name, category) values
('Squat', 'Powerlifting'),
('Bench Press', 'Powerlifting'),
('Deadlift', 'Powerlifting'),
('Overhead Press', 'Strength'),
('Barbell Row', 'Strength'),
('Pull Up', 'Strength'),
('Dumbbell Curl', 'Hypertrophy');

-- Create likes table
create table public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  log_id bigint references public.logs(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, log_id)
);

-- Enable RLS
alter table public.likes enable row level security;

-- Policies
create policy "Likes are viewable by everyone" on public.likes
  for select using (true);

create policy "Users can insert their own likes" on public.likes
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own likes" on public.likes
  for delete using (auth.uid() = user_id);

-- Body Measurements
create table public.body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  weight numeric not null,
  unit text default 'lbs',
  notes text,
  date_logged timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.body_measurements enable row level security;

create policy "Users can view their own body measurements" on public.body_measurements
  for select using (auth.uid() = user_id);

create policy "Users can insert their own body measurements" on public.body_measurements
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own body measurements" on public.body_measurements
  for update using (auth.uid() = user_id);

create policy "Users can delete their own body measurements" on public.body_measurements
  for delete using (auth.uid() = user_id);

-- Comments
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  log_id bigint references public.logs(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Users can insert their own comments."
  on comments for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own comments."
  on comments for delete
  using ( auth.uid() = user_id );
